### ISSUE TITLE
Using setup-all.sh on windows I get the following error

### ISSUE THREAD

**Issue by tmakaro** [FreeRDP/FreeRDP-WebConnect#106]
Can anyone tell me why I am getting this error using setup-al.sh on windows 10?

C:\FreeRDP-WebConnect\setup-all.sh: line 239: make: command not found
Unable to build ehs package. Exiting...

Afterwards I installed gnuwin32 and added it to my PATH but then when make is executed on line 239 it just says it can't find the make file.

Has anyone successfully built this project on windows????

**Comment by c64cosmin** [comment]
The .sh scripts are intended for the Linux build. On Windows you need to run the cmake and then open the with VS 2015 and build.

**Comment by c64cosmin** [comment]
@tmakaro or if you want the software you could download the build from here.
http://www.cloudbase.it/freerdp-html5-proxy-windows/

**Comment by tmakaro** [comment]
That got me further. Thanks.
