### ISSUE TITLE
Tab Not Captured in Web App

### ISSUE THREAD

**Issue by necouchman** [FreeRDP/FreeRDP-WebConnect#113]
The tab key does not seem to be captured within the app - instead of tabbing through fields within the RDP connection, it tabs through the web browser.

**Comment by c64cosmin** [comment]
Of course. That is expected behaviour, the browser does not catch properly system key binding (for security reasons)
Try my branch https://github.com/c64cosmin/FreeRDP-WebConnect it will get upstream quite soon. It has a binding for alt+tab combination. Enjoy!

**Comment by necouchman** [comment]
Kind of what I figured.  Thanks.
