### ISSUE TITLE
Is there way to use this?

### ISSUE THREAD

**Issue by b1rdex** [FreeRDP/FreeRDP-WebConnect#118]
Yesterday I started to find a way to get wsgate working.
I need wsgate web interface to integrate to my web app.

So far I tried this things:
### first try

Debian 8 compile from `master` branch. It's not possible with bug in locating `ehs` dep (which auto compiles and installes to system nice).
### second try

Debian 8 deb packages from http://freerdp.net/download.html
That's not possible, since maintainer key became expired month ago.
And those packages was built in 2012. Too old and not installable.
### third try

Debian 8 compile from https://github.com/c64cosmin/FreeRDP-WebConnect/tree/plugin
Compilation succeed. But wait, I read `setup-all.sh` and it has no `install` target (and makefile hasn't in too).
Ok, I `cd`ed to `build` folder and tried to run. But I think there is problems because of no `install` step.
I made `ini` config from sample. And started `wsgate`. Ok, I got `wsgate` in processes, but still no webinterface.
Moved  `webroot` to `nginx` host. Got web interface. But it's broken, `%JSDEBUG%` is all over the page and that's not stripped. Ok, `make` in `webroot` must be doing this (the only target is `strip…`). No, that's not working.
Ok, cleared this `%JSDEBUG%` myself. Interface appeared, but there is javascript error: `cookie[i]` and nothing working.
### fourth try

Windows 10. Downloaded installer from http://freerdp.net/download.html
Install, next, next. Wait, how to launch? Must be service. Going to `services`, click manual launch.
`Service closed after start`. Must be some bug. Opened administrator cmd and

```
C:\WINDOWS\system32>"C:\Program Files (x86)\FreeRDP-WebConnect\bin\wsgate.exe"
Could not read config file '/usr/i686-w64-mingw32/sys-root/mingw/etc/wsgate.ini'.
```

Oh nice. Copied default config to `C:/usr/i686-w64-mingw32/sys-root/mingw/etc/wsgate.ini`.
Next run — openssl cert error. Ok, I don't need ssl so just strip that from config.
Next run — bla bla bind. Ok, I'm already admin but can't bind to 80? Strange. Changed to 8000.
Oh, it ran! `http://localhost:8000` and nothing there. Checked processes, it's really listening 8000.
Copied webroot to my nginx host. Oh, there is `%JSDEBUG%` again…

Time to give up? Or does anybody have some magic recipe?

cc @c64cosmin

**Comment by c64cosmin** [comment]
Well %JSDEBUG% is being stripped by wsgate itself, you don't need a webhost for wsgate, it does it itself, you need to specify in the .ini file
`[http]`
`documentroot=<path>\FreeRDP-WebConnect\WebRoot\`

Also if you want FreeRDP-WebConnect, we have a .msi in here https://www.cloudbase.it/downloads/FreeRDPWebConnect_Beta.msi
It's up to date.

**Comment by b1rdex** [comment]
> Well %JSDEBUG% is being stripped by wsgate itself, you don't need a webhost for wsgate
But I haven't got it working.

> msi
What about linux version? What system should I try to 100% get it working?

**Comment by b1rdex** [comment]
Msi is working good! Looking for some working linux version.

**Comment by alexpilotti** [comment]
This is a very old unmaintained version: http://freerdp.net/download.html
For latest MSI builds: https://cloudbase.it/freerdp-html5-proxy-windows/
