### ISSUE TITLE
wsgate.ini settings such as hostname, user and password are not properly loaded when open the http://ip:8000

### ISSUE THREAD

**Issue by akashtalole** [FreeRDP/FreeRDP-WebConnect#119]

**Comment by c64cosmin** [comment]
Can you show me the .ini file that you have?

**Comment by akashtalole** [comment]
Problem  is in wsgate_main.cpp code
if(externalRequest)
                    {
                        string dtsize(request->FormValues("dtsize").m_sBody);
                        string port(request->FormValues("port").m_sBody);

                        replace_all(body, "%COOKIE_LASTUSER%", request->FormValues("user").m_sBody);
                        replace_all(body, "%COOKIE_LASTPASS%",  base64_decode(request->FormValues("pass").m_sBody)); // Passw0rd
                        replace_all(body, "%COOKIE_LASTHOST%", request->FormValues("host").m_sBody);
                        replace_all(body, "%COOKIE_LASTPCB%", request->FormValues("pcb").m_sBody);
                        replace_all(body, "var externalConnection = false;", "var externalConnection = true;");
                    }
                    else
                    {
                        tmp.assign(m_bOverrideRdpUser ? "<predefined>" : request->Cookies("lastuser"));
                        replace_all(body, "%COOKIE_LASTUSER%", tmp);
                        tmp.assign(m_bOverrideRdpUser ? "disabled=\"disabled\"" : "");
                        replace_all(body, "%DISABLED_USER%", tmp);
                        tmp.assign(m_bOverrideRdpPass ? "SomthingUseless" : base64_decode(request->Cookies("lastpass")));
                        replace_all(body, "%COOKIE_LASTPASS%", tmp);
                        tmp.assign(m_bOverrideRdpPass ? "disabled=\"disabled\"" : "");
                        replace_all(body, "%DISABLED_PASS%", tmp);

                        tmp.assign(m_bOverrideRdpHost ? "<predefined>" : request->Cookies("lasthost"));
                        replace_all(body, "%COOKIE_LASTHOST%", tmp);
                        tmp.assign(m_bOverrideRdpHost ? "disabled=\"disabled\"" : "");
                        replace_all(body, "%DISABLED_HOST%", tmp);

                        tmp.assign(request->Cookies("lastpcb"));
                        replace_all(body, "%COOKIE_LASTPCB%", tmp);
                        tmp.assign("");
                        replace_all(body, "%DISABLED_PCB%", tmp);
                    }

when predefined values are set in wsgate.ini on UI it shows "<predefined>" in host and other field. So that it can not connect to the backend. When we predefined the values in wsgate.ini then UI should take values from wsgate.ini

**Comment by c64cosmin** [comment]
@akashtalole That part of the code will become obsolete in the near future because we will strip out the webhosting of wsgate, so you would be able to use a dedicated host, like Apache or IIS. Also use my branch because is more up to date (we haven't tested it thoroughly, so we will merge it soon on master). Have you managed to achieve what you planned?

**Comment by akashtalole** [comment]
Yes I managed .
