### ISSUE TITLE
Javascript issue

### ISSUE THREAD

**Issue by b1rdex** [FreeRDP/FreeRDP-WebConnect#121]
```
<form onkeypress="if (event.keyCode == 13) { document.getElementById('rdpconnect').focus();document.getElementById('rdpconnect').click(); return event.preventDevault();}">
```

must be `event.preventDefault`.

@c64cosmin (assuming you're main contributor for this thing) here is link based on your fork: https://github.com/c64cosmin/FreeRDP-WebConnect/blob/f2ab584abff3ecd6405eb5a3e3c4f77aacc6f9d1/wsgate/webroot/index-debug.html#L527

**Comment by c64cosmin** [comment]
Thank you for pointing that! That was there for quite a while, haha.
