### ISSUE TITLE
Wsgate service on windows eating cpu

### ISSUE THREAD

**Issue by b1rdex** [FreeRDP/FreeRDP-WebConnect#122]
1. Launch service
2. Connect using weinterface
3. Picture is static — no frames transmitted over time after initial draw

Service is consuming 100% of 1 cpu core in this state. And this is not increased when there is some draw activity.
I think this is some `while(true)` bug and should be fixed.

How can I help to solve the problem?

This is idle state
![image](https://cloud.githubusercontent.com/assets/312855/11710693/d93975b6-9f6c-11e5-881f-60b5b0b02aef.png)

This is connected state with no screen activity (static image)
![image](https://cloud.githubusercontent.com/assets/312855/11710740/130d708a-9f6d-11e5-9ec3-1698179f9c18.png)

This is connected state with screen activity (some animations)
![image](https://cloud.githubusercontent.com/assets/312855/11710774/53df89b8-9f6d-11e5-81d8-b55fe71b5dfc.png)

I think this is related to gate-rdp connection and not client-gate. But connected rdp itself must not use 100% cpu.

**Comment by c64cosmin** [comment]
So it does, apparently there was a while loop where the CPU was put to sleep but for a really short interval (i.e. usleep(100)), pull the branch and recompile (I changed the interval to usleep(1000), that should do it.

**Comment by b1rdex** [comment]
Will your branch merged? I'm now on official build and don't want to build
on windows. And can't get it working on Linux.

**Comment by c64cosmin** [comment]
I don't know when my branch will get merged (also build the .msi), but if you want you can email me, to guide you to build on linux, or a binary fix for windows.

**Comment by c64cosmin** [comment]
CPU usage now is at ~0.3% for a single connection.

**Comment by b1rdex** [comment]
Closing as fixed.
