### ISSUE TITLE
FreeRDP use Authority signed SSL certificate

### ISSUE THREAD

**Issue by alexmela78** [FreeRDP/FreeRDP-WebConnect#139]
I want replace self-sign certificate with a Authority signed certificate.
This certificate is already emitted so I have CA boundle, crt and private key.

How I can generate cer to put in wsgate etc directory?

I try a lot of way but service doesn't start with error in event viewer 
Error while loading certificate: error:0906D06C:PEM routines:PEM_read_bio:no start lineerror:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib

can anyone help me?

thanks

Alessandro Melani

**Comment by c64cosmin** [comment]
Convert the .crt to .cer then copy it in the /etc.

You can use the OpenSSL binaries: https://info.ssl.com/how-to-der-vs-crt-vs-cer-vs-pem-certificates-and-how-to-conver-them/
Or you could use the certificate exporter from Windows: https://support.software.dell.com/kb/sw13147

**Comment by alexmela78** [comment]
I use procedure to convert crt to cer .. but now when I try to start service .. I receive this error:
Error while loading private key: error:0906D06C:PEM routines:PEM_read_bio:no start lineerror:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib

**Comment by c64cosmin** [comment]
Look into the private key file and make sure it starts with
-----BEGIN RSA PRIVATE KEY-----
The "-" and spaces included and ends with
-----END RSA PRIVATE KEY-----

Must resemble something like this.
[EXAMPLE PRIVATE KEY](https://657cea1304d5d92ee105-33ee89321dddef28209b83f19f06774f.ssl.cf1.rackcdn.com/Windows1-2717834b7ff327957bb3d28e8c46206cb6adddd71e3ff995a1798a00b5304663.png)

If that doesn't work, open you private key with a text editor that can "see" special characters (ie. ^M or carriage return). Make sure that each text line doesn't end with carriage return, if it does, remove them.

**Comment by alexmela78** [comment]
Thanks a lot.. now it works.
