### ISSUE TITLE
Cannot successfully run ./configure on FreeRDP-Webconnect.

### ISSUE THREAD

**Issue by beardflex** [FreeRDP/FreeRDP-WebConnect#53]
Hi,

I'm trying to deploy FreeRDP-Webconnect with vmconnect support on RedHat 6.

I downloaded the sources from the master repo, and can build all the prerequisite libraries , but when I try to configure FreeRDP-Webconnect I get:

checking for getEHSconfig in -lehs... no
checking ehs.h usability... no
checking ehs.h presence... yes
configure: WARNING: ehs.h: present but cannot be compiled
configure: WARNING: ehs.h:     check for missing prerequisite headers?
configure: WARNING: ehs.h: see the Autoconf documentation
configure: WARNING: ehs.h:     section "Present But Cannot Be Compiled"
configure: WARNING: ehs.h: proceeding with the preprocessor's result
configure: WARNING: ehs.h: in the future, the compiler will take precedence
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to fritz@fritz-elfert.de ##
configure: WARNING:     ## ------------------------------------ ##
checking for ehs.h... yes
configure: error: Mandatory EHS development package not found

EHS is installed and the headers are available in /usr/local/include/ehs

Any help would be appreciated.

**Comment by suslikas** [comment]
I'm try use 

```./install_prereqs.sh
./setup-all.sh -f```

on vanilla Centos 6.5, 7, Ubuntu Server 12 and 14. Lot of errors end fail on end. If Install rpm for Centos 6, web interface work, but you can not login. All work only for Windows, but something wrong with Openstack Implementation, not work properly links like "http://1.1.1.1:8000/?token=e79bc0e5-1057-45d0-8b14-abf9e64eb315"
