### ISSUE TITLE
Could not connect to RDP backend

### ISSUE THREAD

**Issue by rushikeshjadhav** [FreeRDP/FreeRDP-WebConnect#95]
For both valid and invalid login details, I'm getting below error in logs.
JS: C o u l d   n o t   c o n n e c t   t o   R D P   b a c k e n d . 

On another installation I'm getting
wsgate[19549]: segfault at 0 ip 0000000000494c0c sp 00007fd6e1204b30 error 6 in wsgate[400000+10e000] 
and wsgate program dies. Object dump trace might help here but its too much effort for me :(

In both installations  index*.html : var wsBase = "%WSURI%";
and when we open the page http://server-ip:port in browser WSURI should be ws://server-ip:port/wsgate but it gets set as ws://server-ip:port:port/wsgate

Kindly consider if I'm mixing two issues together.

**Comment by c64cosmin** [comment]
Can you tell me more about your setup, so I can reproduce your problem?

**Comment by rushikeshjadhav** [comment]
Re: C o u l d n o t c o n n e c t t o R D P b a c k e n d 
I had to disable NLA on windows host and enable nonla=true on linux, this seems to have worked so far with few new issues such as "Server exited with code 0xb" but we can discuss that later.

The segfault is on CentOS7 build. As mentioned in another issue I've used https://gist.github.com/rushikeshjadhav/c798005557a5fec8c58e to let it continue.

**Comment by c64cosmin** [comment]
I've tried Web-Connect on CentOS 7, it seems to work. Can you be more specific with what you have done so I can reproduce the problem.

**Comment by rushikeshjadhav** [comment]
Hi @c64cosmin, it builds fine however there are 2 concerns. 

(1) install_prereqs.patch mentioned in https://gist.github.com/rushikeshjadhav/c798005557a5fec8c58e suggests that the devtools installation is unnecessary as CentOS7 already has gcc 4.8.3

(2) setup-all.sh.patch mentioned in same patch, make the git checkout of casablanca in /root/prereqs/, without it the checkout happens at /root/ which I think wasnt intended originally.

Does RDP to host and guest VM works for you without segfault ?

**Comment by c64cosmin** [comment]
The scripts have no issue like that. It has been taken care of about a week ago. Make sure you are up to date with the repository. Also that was unrelated to the topic of this issue.

I did test wsgate on CentOS7 and ubuntu14.04LTS and they both work fine. If you want me to be helpful you need to inform me on what you've did. I need to replicate your settings so I can get the same error.

Don't forget to pull the last commits.

**Comment by rushikeshjadhav** [comment]
I'll do test on a clean CentOS6 & CentOS7 machine. Closing this issue as the problem is more related to compilation.
