### ISSUE TITLE
How to compile windows variant for wsgate ?

### ISSUE THREAD

**Issue by rushikeshjadhav** [FreeRDP/FreeRDP-WebConnect#98]
Build instructions mentioned are for linux. Are there any different instructions for Windows build ?

**Comment by c64cosmin** [comment]
We're using continuous integration for the Windows platform.
So you can download it in here : http://www.cloudbase.it/freerdp-html5-proxy-windows/

**Comment by rushikeshjadhav** [comment]
If I want to test my code changes in wsgate on windows, how would I do that ? I'm modifying wsgate to do additional work before opening console.

**Comment by c64cosmin** [comment]
The same way like in linux, you clone, you run the cmake file and then build.

**Comment by rushikeshjadhav** [comment]
Could anyone please share the Development setup instructions for this ? Being a linux user, I have less idea on setting this up.

**Comment by tmakaro** [comment]
I'm trying the following which is failing. Can someone please help me:

C:\FreeRDP-WebConnect>setup-all.sh
Welcome to Git (version 1.9.0-preview20140217)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
---- Fetching webconnect dependencies ehs and FreeRDP into /c/Users/Troy/prereqs ----
~ /c/FreeRDP-WebConnect
---- Checking out ehs trunk code ----
Cloning into 'EHS'...
remote: Counting objects: 1128, done.
emote: Total 1128 (delta 0), reused 0 (delta 0), pack-reused 1128
Receiving objects: 100% (1128/1128), 402.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (829/829), done.
Checking connectivity... done.
---- Starting ehs build ----
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23026.0
-- The CXX compiler identification is MSVC 19.0.23026.0
-- Check for working C compiler using: Visual Studio 14 2015
-- Check for working C compiler using: Visual Studio 14 2015 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 14 2015
-- Check for working CXX compiler using: Visual Studio 14 2015 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using MSVC dynamic runtime
-- MSVC: using dynamically-linked runtime (/MD and /MDd).
-- Found WinSDK: C:/Program Files (x86)/Windows Kits/8.1/Include/um
-- Looking for Windows.h
-- Looking for Windows.h - found
-- Looking for winsock2.h
-- Looking for winsock2.h - found
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - not found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - not found
-- Looking for syslog.h
-- Looking for syslog.h - not found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - not found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - not found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/wait.h
-- Looking for sys/wait.h - not found
-- Looking for termios.h
-- Looking for termios.h - not found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for execinfo.h
-- Looking for execinfo.h - not found
-- Looking for conio.h
-- Looking for conio.h - found
-- Looking for vfork.h
-- Looking for vfork.h - not found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pid_t
-- Check size of pid_t - failed
-- Check size of size_t
-- Check size of size_t - done
Include dir:
CMake Error at c:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: THREADS_PTHREADS_WIN32_LIBRARY
  THREADS_PTHREADS_INCLUDE_DIR)
Call Stack (most recent call first):
  c:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindThreads.cmake:278 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:291 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Troy/prereqs/EHS/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Troy/prereqs/EHS/build/CMakeFiles/CMakeError.log".
Unable to build ehs package. Exiting...

**Comment by tmakaro** [comment]
@rushikeshjadhav Have you had any success on building the code for windows? Having just done it myself, I may be able to help you. If what you want is to build on linux for windows then I can't help you.  I'm strictly a windows developer.

**Comment by ferslash** [comment]
@tmakaro, yes please how did you compiled for windows, i wold like to replace the bunny image for instance for something different, for instance my software brand, like the guys of cloudbase :D

**Comment by c64cosmin** [comment]
@ferslash You need to run cmake and then compile.

@rushikeshjadhav I have tested if build succeds on several Linux distributions and it worked with no problem. The difference was we used freshly spawned VMs, with a clean new setup.

@ferslash @rushikeshjadhav For windows you could refer to the closed issues raised by @tmakaro.

**Comment by rushikeshjadhav** [comment]
Was able to get it working on Fresh CentOS7 along with modifications. Closing this one.
